name : git workshop demo

on:
  push:
    branches:
        - 'feature/**'
        - 'bugfix/**'
        - 'chore/**'

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "HELLO GITHUB ACTION"


